### PR TITLE
Add more keywords as npm search is case sensitive

### PR DESCRIPTION
**Pull request by clarkie**
I couldn't find this library on npm but it was exactly what I was looking for. The only way I found out was because a friend told me over sushi at SushiJS.

### CODE REVIEW

**Comment by blaw2422** [comment]
maybe go ahead and add `dynamoDb` ?

**Comment by clarkie** [comment]
dYnAmOdB? :smile:

**Comment by clarkie** [comment]
https://github.com/npm/newww/issues/501

**Comment by clarkie** [comment]
I've 'forked' vogels as https://www.npmjs.com/package/dynogels and updated the keywords there.

**Pull request closed without merging**
